### ISSUE TITLE
[Feature] 로딩 컴포넌트 구현

### ISSUE THREAD

**Issue by egg-silver** [Fur-Fact/Frontend#21]
**TODO List**

- [ ] 메인 페이지 스켈레톤 ui
- [ ] 결과 조회 페이지 로딩 스피너
- [ ] 알림 페이지 새로고침 버튼 및 누르면 로딩 스피너

**참고 자료**
기능과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
