### ISSUE TITLE
[Feature] 동물 추가 및 수정 기능 구현

### ISSUE THREAD

**Issue by BellYun** [Fur-Fact/Frontend#9]
**기능에 대한 설명**
새로운 기능에 대한 명확하고 간결한 설명을 작성해 주세요.
(예: 로그인 이중 인증 구현)

**TODO List**

- [x] 동물 추가 기능을 구현
- [x] 동물 추가 API연동
- [x] 동물 목록 조회 API 연동
- [x] 동물 수정 API 연동

**참고 자료**
기능과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
